### ISSUE TITLE
Add support for buildStatisticValue to TeamCity

### ISSUE THREAD

**Issue by flcdrg** [agc93/Cake.BuildSystems.Module#11]
As demonstrated in this [SO answer](https://stackoverflow.com/a/44676259/25702), it would be nice to support TeamCity's buildStatisticValue service message

**Comment by agc93** [comment]
I've added this functionality in 87bf69b683f7391a3a4a1b869a0ff74a830059b2.

@flcdrg or @pitermarx : Can one of you guys please try out the [latest prerelease package (0.2.0-unstable0020)](https://www.nuget.org/packages/Cake.BuildSystems.Module/0.2.0-unstable0020) on TeamCity and see if it works?

I don't have a TC instance to test on right now..

**Comment by flcdrg** [comment]
Looks ok to me
