### ISSUE TITLE
TFBuildEngineModule is `internal`

### ISSUE THREAD

**Issue by agc93** [agc93/Cake.BuildSystems.Module#2]
No reason for `TFBuildEngineModule` to be `internal`. Should make it public, and will also make @patriksvensson happy :smile:

**Comment by patriksvensson** [comment]
Should also rename it to `TFBuildModule` 😄

**Comment by agc93** [comment]
@patriksvensson [Version 0.1.2](https://www.nuget.org/packages/Cake.BuildSystems.Module/0.1.2) has been released and makes the newly-renamed `TFBuildModule` class `public` 👍

**Comment by patriksvensson** [comment]
@agc93 Sweet :)
